<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Registro_bg-pt-tertiary rounded-lg text-w_5995c9</name>
   <tag></tag>
   <elementGuidId>5fd8dfaa-c589-4332-8e19-d332bb6b9714</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;ACCESO&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b1cbc152-0d94-4c1b-aa1b-0b5744b67c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-pt-tertiary rounded-lg text-white p-[6px] uppercase text-sm whitespace-nowrap</value>
      <webElementGuid>204b0670-946c-4cb1-b3c3-84b74f6c07b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/app-qa/saceq/ingreso</value>
      <webElementGuid>d5762f5a-7e1a-40a0-ab81-4811fc8abb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACCESO</value>
      <webElementGuid>7e2aa1b1-5143-40ad-b24c-4e99d97f4fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;flex items-center h-[48px] pt-[15px] gap-2 sticky top-0 z-80 bg-white&quot;]/a[@class=&quot;bg-pt-tertiary rounded-lg text-white p-[6px] uppercase text-sm whitespace-nowrap&quot;]</value>
      <webElementGuid>49e7856e-0be9-46d7-b8bc-2f526552a182</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/a[2]</value>
      <webElementGuid>64d94ba2-46c7-4738-8b0d-bab951ee4ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ACCESO')]</value>
      <webElementGuid>db513515-259f-4559-bebb-77ce530f60a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registro'])[1]/following::a[1]</value>
      <webElementGuid>0ab3590c-ca99-4232-801d-6a5926825829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v1.3.0'])[1]/preceding::a[2]</value>
      <webElementGuid>acbaaa72-5405-49c1-9d26-b9ab9fed9887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCESOS DIRECTOS'])[1]/preceding::a[2]</value>
      <webElementGuid>6f5f4429-7be8-476f-bd09-e8f3edfdbea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ACCESO']/parent::*</value>
      <webElementGuid>a93a6cfd-aa4b-45a9-bf81-bbe73e1c7901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/app-qa/saceq/ingreso')]</value>
      <webElementGuid>d77ccc33-24c2-4f9b-ad92-57e1fb5a4b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>a609f94c-bc8e-4557-8226-5841f5ff3e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/app-qa/saceq/ingreso' and (text() = 'ACCESO' or . = 'ACCESO')]</value>
      <webElementGuid>da31d9ae-da77-4ed9-af03-31bdccc0d0ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
