<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Registro_bg-pt-tertiary rounded-lg text-w_5995c9</name>
   <tag></tag>
   <elementGuidId>5fd8dfaa-c589-4332-8e19-d332bb6b9714</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;ACCESO&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>416028e8-f923-486e-baac-78813c02188f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-pt-tertiary rounded-lg text-white p-[6px] uppercase text-sm whitespace-nowrap</value>
      <webElementGuid>c376a2ca-8282-46be-a14a-1374cdbabe46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/app-qa/saceq/ingreso</value>
      <webElementGuid>c66e60da-778b-4c9b-adf8-6dd3645c8a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACCESO</value>
      <webElementGuid>322e5cd2-d14a-422b-a5ac-eb97b7a8f091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;flex items-center h-[48px] pt-[15px] gap-2 sticky top-0 z-80 bg-white&quot;]/a[@class=&quot;bg-pt-tertiary rounded-lg text-white p-[6px] uppercase text-sm whitespace-nowrap&quot;]</value>
      <webElementGuid>ac5d9682-023e-4cb6-bf0d-37d9f0820791</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/a[2]</value>
      <webElementGuid>9174cc23-bc3a-4c14-9c01-5ffb9513e450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ACCESO')]</value>
      <webElementGuid>8123ef29-d10d-4ded-b4fc-963f2a0c9994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registro'])[1]/following::a[1]</value>
      <webElementGuid>f23a31e3-8102-47f9-b3fb-825737b351bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v1.3.0'])[1]/preceding::a[2]</value>
      <webElementGuid>2f715147-072c-4077-9198-7511ba77a2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCESOS DIRECTOS'])[1]/preceding::a[2]</value>
      <webElementGuid>6c8beab7-168d-44b7-9534-d844f02589ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ACCESO']/parent::*</value>
      <webElementGuid>731e138a-d878-4978-91dc-addd1d24d793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/app-qa/saceq/ingreso')]</value>
      <webElementGuid>46b6c193-ac63-4b0e-9d8b-377c0c43bc2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>6d3447e0-e1ab-49ed-afe2-60043e617efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/app-qa/saceq/ingreso' and (text() = 'ACCESO' or . = 'ACCESO')]</value>
      <webElementGuid>c67b39d7-47a9-4c35-a499-48d1bd090e17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
