<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_v1.3.0_w-full h-auto rounded-lg</name>
   <tag></tag>
   <elementGuidId>0b23e0e3-5f81-417f-8019-f8ae4e1a0580</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[4]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.w-full.h-auto.rounded-lg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Descripción de la imagen&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2d8e7f73-647c-4b9e-b1ae-3c2e4b042820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Descripción de la imagen</value>
      <webElementGuid>d37afaa7-5764-4bb2-b45e-d10b0c801470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>e32d8b7b-df9c-4a75-8c57-2bce2d368b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1920</value>
      <webElementGuid>e0aa88bf-67ba-4114-91a4-dd559699a8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>0d086189-b533-4295-b26b-d877cba0687d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>1c25058c-31e5-48fc-b881-11aff8ccd549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f377a806-59da-49a3-a58d-802ada1f7fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-auto rounded-lg</value>
      <webElementGuid>731c19c0-0c46-4c27-9c97-c43390780e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/app-qa/saceq/_next/image?url=%2Fapp-qa%2Fsaceq%2Fassets%2Fmain%2FBANNER-GRANDE.jpg&amp;w=1920&amp;q=75 1x, /app-qa/saceq/_next/image?url=%2Fapp-qa%2Fsaceq%2Fassets%2Fmain%2FBANNER-GRANDE.jpg&amp;w=3840&amp;q=75 2x</value>
      <webElementGuid>002c866c-574e-4abf-afa9-11e3a040ce05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/app-qa/saceq/_next/image?url=%2Fapp-qa%2Fsaceq%2Fassets%2Fmain%2FBANNER-GRANDE.jpg&amp;w=3840&amp;q=75</value>
      <webElementGuid>a0ed93cd-b305-4de3-b508-ba3b24da8623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;main&quot;]/div[@class=&quot;main__container&quot;]/img[@class=&quot;w-full h-auto rounded-lg&quot;]</value>
      <webElementGuid>51fb5d8a-2df9-433d-952e-247fa6d3a797</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[4]/div/img</value>
      <webElementGuid>af6aef89-da31-49b8-abde-625089ab0f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Descripción de la imagen']</value>
      <webElementGuid>0edb3382-89f9-47b2-bbf3-c0e57058659c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>d3b6de74-85a4-4dbf-92fd-bed366e6e428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Descripción de la imagen' and @src = '/app-qa/saceq/_next/image?url=%2Fapp-qa%2Fsaceq%2Fassets%2Fmain%2FBANNER-GRANDE.jpg&amp;w=3840&amp;q=75']</value>
      <webElementGuid>22998b13-edd9-4ef4-a778-e980a43c7e09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
