<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_v1.3.0_w-full h-auto rounded-lg</name>
   <tag></tag>
   <elementGuidId>0b23e0e3-5f81-417f-8019-f8ae4e1a0580</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[4]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.w-full.h-auto.rounded-lg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Descripción de la imagen&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1fd4c4f5-e0ef-4a6d-9287-e7ba7558a90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Descripción de la imagen</value>
      <webElementGuid>0c4d050c-0fa1-4405-b694-6b22d0e7aae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>02341f33-dbd7-4d79-b043-11ad2de4a83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1920</value>
      <webElementGuid>59ff3afa-d1e1-47dd-97ed-983473a1a43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>8ee0de33-3962-4928-ae7c-7c26f93bfa08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>bb2729a0-d4fc-4711-bfba-84fafb0c0df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3dacdd0b-3e92-4860-ba5e-209157bc7301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-auto rounded-lg</value>
      <webElementGuid>9c091dc0-02fd-43ea-ba07-132c2e47f6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/app-qa/saceq/_next/image?url=%2Fapp-qa%2Fsaceq%2Fassets%2Fmain%2FBANNER-GRANDE.jpg&amp;w=1920&amp;q=75 1x, /app-qa/saceq/_next/image?url=%2Fapp-qa%2Fsaceq%2Fassets%2Fmain%2FBANNER-GRANDE.jpg&amp;w=3840&amp;q=75 2x</value>
      <webElementGuid>7295aa46-f7a1-433f-b4a9-ee5018ebb682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/app-qa/saceq/_next/image?url=%2Fapp-qa%2Fsaceq%2Fassets%2Fmain%2FBANNER-GRANDE.jpg&amp;w=3840&amp;q=75</value>
      <webElementGuid>1f9f3798-324a-4e27-98f3-37ba9f3fe9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;main&quot;]/div[@class=&quot;main__container&quot;]/img[@class=&quot;w-full h-auto rounded-lg&quot;]</value>
      <webElementGuid>1cc6e5c8-ee41-4e83-828c-dbd8f4839908</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[4]/div/img</value>
      <webElementGuid>855be35e-d167-4104-b5b0-6867c8527074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Descripción de la imagen']</value>
      <webElementGuid>571bf9c6-59b8-4f06-a6e5-df598347bc96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>7b130178-5652-42cd-aee8-3117d4daceaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Descripción de la imagen' and @src = '/app-qa/saceq/_next/image?url=%2Fapp-qa%2Fsaceq%2Fassets%2Fmain%2FBANNER-GRANDE.jpg&amp;w=3840&amp;q=75']</value>
      <webElementGuid>0a0fe623-8d47-4cd1-94cd-b95d496aae5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
