<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OFICINA VIRTUAL_RFC</name>
   <tag></tag>
   <elementGuidId>4bc3e677-2e8b-41a6-b004-807a3c2260cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='RFC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;RFC&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9709d22-2e74-4076-886f-95730dd3b093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RFC</value>
      <webElementGuid>bf46f37b-141d-4949-84ee-78075785510b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>82602de4-037a-4b22-bc9e-2e5205b45bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8edbfaa9-c5c2-4aae-9755-61db48d596dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>transition-colors duration-200 tracking-wider border-[2.5px]
          border-gray-primary 
          null
          white
          rounded-[25px] text-[12px] w-full min-h-[40px] h-full pl-3 pr-9 focus:outline-none font-semibold font_aken
          text-pt-gray-300</value>
      <webElementGuid>ae80a6b9-32fc-4a3d-970a-5cc7f30fa670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;bg-pt-gray-100 min-h-screen&quot;]/div[@class=&quot;min-h-screen w-full flex flex-col items-center pt-24&quot;]/div[@class=&quot;bg-white lg:p-24 p-8 w-[60%] max-w-[838px] rounded-[40px] justify-evenly h-auto min-h-[400px] flex flex-col&quot;]/div[1]/div[@class=&quot;'grid' grid-cols-6 mas&quot;]/div[@class=&quot;py-8 col-start-4 col-span-6&quot;]/div[@class=&quot;flex justify-center items-center w-full&quot;]/div[@class=&quot;relative items-center my-3 h-[40px] w-full w-7/12&quot;]/input[@class=&quot;transition-colors duration-200 tracking-wider border-[2.5px]
          border-gray-primary 
          null
          white
          rounded-[25px] text-[12px] w-full min-h-[40px] h-full pl-3 pr-9 focus:outline-none font-semibold font_aken
          text-pt-gray-300&quot;]</value>
      <webElementGuid>3dba1a86-c039-4dff-b983-f3a2219f183c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='RFC']</value>
      <webElementGuid>bbc1589e-bd67-46cd-bdcb-2bc824a78eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>0a5ef8a6-4945-46dc-be41-dac30cab65e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>348d5f15-107d-40f0-be54-7b1d395ab587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'RFC']</value>
      <webElementGuid>271c90a0-96ae-4c4b-b47c-f94660692ce7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
