<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OFICINA VIRTUAL_RFC</name>
   <tag></tag>
   <elementGuidId>4bc3e677-2e8b-41a6-b004-807a3c2260cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='RFC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;RFC&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3dfaf91-4e10-492a-bc01-70d43d3c1231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RFC</value>
      <webElementGuid>0c7acc1c-b691-43c6-b9a4-2f1a533375d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>9de26a7a-08f3-418a-992d-6ef0bf86d798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>14b2d843-7007-4cdb-be9b-b77e50d1b6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>transition-colors duration-200 tracking-wider border-[2.5px]
          border-gray-primary 
          null
          white
          rounded-[25px] text-[12px] w-full min-h-[40px] h-full pl-3 pr-9 focus:outline-none font-semibold font_aken
          text-pt-gray-300</value>
      <webElementGuid>947bcde1-98a7-4f37-8d57-b367343bbd2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;bg-pt-gray-100 min-h-screen&quot;]/div[@class=&quot;min-h-screen w-full flex flex-col items-center pt-24&quot;]/div[@class=&quot;bg-white lg:p-24 p-8 w-[60%] max-w-[838px] rounded-[40px] justify-evenly h-auto min-h-[400px] flex flex-col&quot;]/div[1]/div[@class=&quot;'grid' grid-cols-6 mas&quot;]/div[@class=&quot;py-8 col-start-4 col-span-6&quot;]/div[@class=&quot;flex justify-center items-center w-full&quot;]/div[@class=&quot;relative items-center my-3 h-[40px] w-full w-7/12&quot;]/input[@class=&quot;transition-colors duration-200 tracking-wider border-[2.5px]
          border-gray-primary 
          null
          white
          rounded-[25px] text-[12px] w-full min-h-[40px] h-full pl-3 pr-9 focus:outline-none font-semibold font_aken
          text-pt-gray-300&quot;]</value>
      <webElementGuid>884cfb28-94bc-49e6-8f0e-a4931d5b52ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='RFC']</value>
      <webElementGuid>1196ffbf-1b32-4d3d-9e1e-98d32f06c4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>ba545ee0-a26a-4575-b9aa-3ef784407406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0e93af97-a751-4412-a7a1-ebcbf8d6cbb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'RFC']</value>
      <webElementGuid>1d18be32-97cc-4f0f-a7f1-f6681e06b3df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
